// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/core.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ServiceVendorRequest struct {
	VendorId          string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	VendorName        string `protobuf:"bytes,2,opt,name=vendor_name,json=vendorName" json:"vendor_name,omitempty"`
	VendorDescription string `protobuf:"bytes,3,opt,name=vendor_description,json=vendorDescription" json:"vendor_description,omitempty"`
	VendorLocation    string `protobuf:"bytes,4,opt,name=vendor_location,json=vendorLocation" json:"vendor_location,omitempty"`
	VendorServices    string `protobuf:"bytes,5,opt,name=vendor_services,json=vendorServices" json:"vendor_services,omitempty"`
	VendorEmail       string `protobuf:"bytes,6,opt,name=vendor_email,json=vendorEmail" json:"vendor_email,omitempty"`
	VendorPhone       string `protobuf:"bytes,7,opt,name=vendor_phone,json=vendorPhone" json:"vendor_phone,omitempty"`
	UpdatedAt         string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt         string `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *ServiceVendorRequest) Reset()                    { *m = ServiceVendorRequest{} }
func (m *ServiceVendorRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceVendorRequest) ProtoMessage()               {}
func (*ServiceVendorRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ServiceVendorRequest) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *ServiceVendorRequest) GetVendorName() string {
	if m != nil {
		return m.VendorName
	}
	return ""
}

func (m *ServiceVendorRequest) GetVendorDescription() string {
	if m != nil {
		return m.VendorDescription
	}
	return ""
}

func (m *ServiceVendorRequest) GetVendorLocation() string {
	if m != nil {
		return m.VendorLocation
	}
	return ""
}

func (m *ServiceVendorRequest) GetVendorServices() string {
	if m != nil {
		return m.VendorServices
	}
	return ""
}

func (m *ServiceVendorRequest) GetVendorEmail() string {
	if m != nil {
		return m.VendorEmail
	}
	return ""
}

func (m *ServiceVendorRequest) GetVendorPhone() string {
	if m != nil {
		return m.VendorPhone
	}
	return ""
}

func (m *ServiceVendorRequest) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ServiceVendorRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type ServiceVendorResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ServiceVendorResponse) Reset()                    { *m = ServiceVendorResponse{} }
func (m *ServiceVendorResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceVendorResponse) ProtoMessage()               {}
func (*ServiceVendorResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ServiceVendorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "core.Empty")
	proto.RegisterType((*ServiceVendorRequest)(nil), "core.ServiceVendorRequest")
	proto.RegisterType((*ServiceVendorResponse)(nil), "core.ServiceVendorResponse")
}

func init() { proto.RegisterFile("core/core.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x40, 0x69, 0xbf, 0xb6, 0xd3, 0xb9, 0x9f, 0x58, 0x0c, 0x0a, 0x01, 0x11, 0x75, 0x36, 0xba,
	0x51, 0x11, 0x9f, 0xa0, 0x60, 0x17, 0x82, 0x88, 0x54, 0x70, 0x5b, 0x62, 0x72, 0xd1, 0x40, 0xf3,
	0x63, 0x92, 0x16, 0x7c, 0x54, 0xdf, 0x46, 0x92, 0xdc, 0xe2, 0xe0, 0x66, 0x98, 0x9c, 0x73, 0x16,
	0x37, 0x37, 0x30, 0x93, 0x2e, 0xe0, 0x4d, 0xfe, 0x5c, 0xfb, 0xe0, 0x92, 0x63, 0xa3, 0xfc, 0xdf,
	0x35, 0x30, 0x5e, 0x18, 0x9f, 0xbe, 0xba, 0xef, 0x21, 0x1c, 0xbe, 0x60, 0xd8, 0x6a, 0x89, 0xaf,
	0x68, 0x95, 0x0b, 0x4b, 0xfc, 0xdc, 0x60, 0x4c, 0xec, 0x18, 0xda, 0x6d, 0x01, 0x2b, 0xad, 0xf8,
	0xe0, 0x6c, 0x70, 0xd9, 0x2e, 0xa7, 0x15, 0x3c, 0x28, 0x76, 0x0a, 0xff, 0x49, 0x5a, 0x61, 0x90,
	0x0f, 0x8b, 0x86, 0x8a, 0x9e, 0x84, 0x41, 0x76, 0x05, 0x8c, 0x02, 0x85, 0x51, 0x06, 0xed, 0x93,
	0x76, 0x96, 0xff, 0x2b, 0xdd, 0x41, 0x35, 0xf7, 0xbf, 0x82, 0x5d, 0xc0, 0x8c, 0xf2, 0xb5, 0x93,
	0xa2, 0xb4, 0xa3, 0xd2, 0xee, 0x57, 0xfc, 0x48, 0xb4, 0x17, 0xc6, 0x3a, 0x74, 0xe4, 0xe3, 0x7e,
	0x48, 0x57, 0x89, 0xec, 0x1c, 0xf6, 0x28, 0x44, 0x23, 0xf4, 0x9a, 0x4f, 0x4a, 0x45, 0x53, 0x2f,
	0x32, 0xea, 0x25, 0xfe, 0xc3, 0x59, 0xe4, 0x4d, 0x3f, 0x79, 0xce, 0x88, 0x9d, 0x00, 0x6c, 0xbc,
	0x12, 0x09, 0xd5, 0x4a, 0x24, 0x3e, 0x2d, 0x41, 0x4b, 0x64, 0x9e, 0xb2, 0x96, 0x01, 0x77, 0xba,
	0xad, 0x9a, 0xc8, 0x3c, 0x75, 0xb7, 0x70, 0xf4, 0x67, 0xb5, 0xd1, 0x3b, 0x1b, 0x91, 0x71, 0x68,
	0x0c, 0xc6, 0x28, 0xde, 0x91, 0x36, 0xbb, 0x3b, 0xbe, 0x4d, 0xca, 0x23, 0xdd, 0xfd, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xd4, 0x70, 0xa5, 0x5c, 0xb7, 0x01, 0x00, 0x00,
}
