// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/core-svc.proto

/*
Package core is a generated protocol buffer package.

It is generated from these files:
	core/core-svc.proto
	core/core.proto

It has these top-level messages:
	Empty
	ServiceVendorRequest
	ServiceVendorResponse
*/
package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CoreService service

type CoreServiceClient interface {
	//
	//
	// Creates a  service vendor
	//
	CreateVendorService(ctx context.Context, in *ServiceVendorRequest, opts ...grpc.CallOption) (*ServiceVendorResponse, error)
}

type coreServiceClient struct {
	cc *grpc.ClientConn
}

func NewCoreServiceClient(cc *grpc.ClientConn) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) CreateVendorService(ctx context.Context, in *ServiceVendorRequest, opts ...grpc.CallOption) (*ServiceVendorResponse, error) {
	out := new(ServiceVendorResponse)
	err := grpc.Invoke(ctx, "/core.CoreService/CreateVendorService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoreService service

type CoreServiceServer interface {
	//
	//
	// Creates a  service vendor
	//
	CreateVendorService(context.Context, *ServiceVendorRequest) (*ServiceVendorResponse, error)
}

func RegisterCoreServiceServer(s *grpc.Server, srv CoreServiceServer) {
	s.RegisterService(&_CoreService_serviceDesc, srv)
}

func _CoreService_CreateVendorService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CreateVendorService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.CoreService/CreateVendorService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CreateVendorService(ctx, req.(*ServiceVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVendorService",
			Handler:    _CoreService_CreateVendorService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/core-svc.proto",
}

func init() { proto.RegisterFile("core/core-svc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0x2f, 0x4a,
	0xd5, 0x07, 0x11, 0xba, 0xc5, 0x65, 0xc9, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20,
	0xbe, 0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62, 0x41, 0xa6, 0x7e, 0x62, 0x5e,
	0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x8d, 0x14, 0x3f, 0x5c, 0x23, 0x44,
	0xc0, 0xa8, 0x8d, 0x91, 0x8b, 0xdb, 0x39, 0xbf, 0x28, 0x35, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39,
	0x55, 0xa8, 0x9c, 0x4b, 0xd8, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x35, 0x2c, 0x35, 0x2f, 0x25, 0xbf,
	0x08, 0x26, 0x2c, 0xa5, 0x07, 0xd6, 0x03, 0xe5, 0x42, 0xe4, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b,
	0x4b, 0xa4, 0xa4, 0xb1, 0xca, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0xa9, 0x37, 0x5d, 0x7e,
	0x32, 0x99, 0x49, 0x51, 0x49, 0x06, 0xec, 0xa0, 0x32, 0x43, 0xfd, 0xc2, 0xa2, 0xfc, 0xd2, 0x92,
	0x54, 0xfd, 0x62, 0x88, 0xea, 0x32, 0xb0, 0x6a, 0x2b, 0x46, 0xad, 0x24, 0x36, 0xb0, 0x7b, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x38, 0x4c, 0xec, 0xdb, 0x00, 0x00, 0x00,
}
